### ISSUE TITLE
COPYING file missing

### ISSUE THREAD

**Issue by jdek** [kupix/havoc#1]

**Comment by kupix** [comment]
Hi Josh, thanks for the first havoc issue... can certainly add a COPYING file - what should it say? (Havoc is a combination of work derived from permissively licensed projects together with our own GPLv2 code).

**Comment by enoposix** [comment]
Well I just saw the readme (`See COPYING and the source code for further details.`) so I assumed it just wasn't added.

You could sublicense the more permissively licensed code as GPLv2, but you must still include all the licenses with the distribution. 

You should add files named after the license, for example: LICENSE.MIT, LICENSE.GPLv2 etc, and then clearly in the README state which files are licensed under which license.

Although if it is all your code and you are able to relicense it, then keeping it under the same permissive license would be the more preferred action. (Think about upstream projects not being able to benefit from the work done on this due to the GPLv2 license).

**Comment by jdek** [comment]
It should just explain which files are under which license and include the contents of those licenses. A good example is: https://github.com/KhronosGroup/glslang/blob/master/LICENSE.txt

**Comment by jdek** [comment]
`xbyak*` and `main.c` seem to be under the simplified BSD license, and the rest under GPL2. If you're OK with this then I can make a PR to add a file describing it?
